#!/usr/bin/env bash
# collect_project_deps_installed() 의 Node/Python 보조 lock 소스 5종 검증.
#   yarn.lock(v1/v2+) · pnpm-lock.yaml · poetry.lock · Pipfile.lock · *.egg-info/PKG-INFO
# 에이전트 스크립트에서 함수 정의만 뽑아 eval 하므로 실제 배포되는 코드를 그대로 검사한다.
set -uo pipefail
cd "$(dirname "$0")/.."
AGENT=agent/vuln-inventory-agent.sh
export LC_ALL=C          # sort -u 결과 순서를 로케일과 무관하게 고정

have() { command -v "$1" >/dev/null 2>&1; }
eval "$(sed -n '/^emit_yarn_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_pnpm_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_poetry_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_gemfile_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_gemspec_name() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_jar_meta() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_nested_jars() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^pip_meta_license() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^collect_python_system_meta() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^collect_project_deps_installed() {$/,/^}$/p' "$AGENT")"
SCAN_MAX_FILES=3000; SCAN_MAX_DEPTH=12
# 배포판 파이썬 패스(collect_python_system_meta)는 기본값이 실제 `/usr/lib/python3*` 이다 —
#   픽스처로 돌려놓지 않으면 검사를 도는 호스트에 깔린 패키지가 결과에 섞여 테스트가 흔들린다.
PY_SYS_META_MAX=2000

FIX=$(mktemp -d "tests/.fixtures-nplocks.XXXXXX") || exit 1
LIC=$(mktemp "tests/.lic-nplocks.XXXXXX") || exit 1
trap 'rm -rf "$FIX" "$LIC"' EXIT
mkdir -p "$FIX/yarn1" "$FIX/yarn2" "$FIX/pnpm" "$FIX/poetry" "$FIX/pipenv" \
         "$FIX/py/lib/python3.11/site-packages/oldpkg-1.4.2.egg-info" \
         "$FIX/py/lib/python3.11/site-packages/exprpkg-2.0.0.dist-info" \
         "$FIX/py/lib/python3.11/site-packages/bothpkg-3.1.0.dist-info" \
         "$FIX/py/lib/python3.11/site-packages/clspkg-0.9.0.dist-info" \n         "$FIX/sysdist/distpkg-4.5.6.dist-info" \n         "$FIX/sysdist/legacysys-1.0.egg-info" \n         "$FIX/sysdist/nested/deep-9.9.9.dist-info"

# 1) yarn v1(Classic) — 스코프 패키지의 다중 범위 헤더, 로컬(file:) 항목은 버려야 한다.
cat > "$FIX/yarn1/yarn.lock" <<'EOF'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.0.0, @babel/core@^7.1.0":
  version "7.20.5"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.20.5.tgz#abcdef"
  integrity sha512-deadbeef
  dependencies:
    "@babel/code-frame" "^7.18.6"
    lodash "^4.17.20"

lodash@^4.17.20:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591"

"my-local@file:../local-pkg":
  version "9.9.9"
EOF

# 2) yarn v2+(Berry) — 값에 따옴표가 없고 npm: 프로토콜이 붙는다. __metadata·workspace 는 버린다.
cat > "$FIX/yarn2/yarn.lock" <<'EOF'
__metadata:
  version: 6
  cacheKey: 8

"@types/node@npm:^18.0.0":
  version: 18.11.9
  resolution: "@types/node@npm:18.11.9"
  languageName: node

"chalk@npm:^5.0.0":
  version: 5.1.2
  resolution: "chalk@npm:5.1.2"

"myapp@workspace:.":
  version: 0.0.0-use.local
  resolution: "myapp@workspace:."
EOF

# 3) pnpm — v6 `@` 표기와 v5 슬래시+피어 표기가 섞여도 이름이 안 깨져야 한다.
#    snapshots:(v9) 는 packages 와 같은 키를 중복하므로 읽지 않는다.
cat > "$FIX/pnpm/pnpm-lock.yaml" <<'EOF'
lockfileVersion: '6.0'

dependencies:
  lodash:
    specifier: ^4.17.20
    version: 4.17.21

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}
    dev: false

  /@babel/core@7.20.5:
    resolution: {integrity: sha512-def}

  /@types/babel__core@7.1.20:
    resolution: {integrity: sha512-ghi}

  /react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-jkl}

  /styled-components/5.3.6_react@17.0.2:
    resolution: {integrity: sha512-mno}

  /mylib@file:../mylib:
    resolution: {directory: ../mylib}

snapshots:

  /should-not-appear@9.9.9:
    resolution: {integrity: sha512-zzz}
EOF

# 4) poetry — [[package]] 다중 블록. 하위 테이블([package.dependencies]) 값이 새면 안 된다.
cat > "$FIX/poetry/poetry.lock" <<'EOF'
[[package]]
name = "requests"
version = "2.28.1"
description = "Python HTTP for Humans."
optional = false

[package.dependencies]
certifi = ">=2017.4.17"
urllib3 = {version = ">=1.21.1,<1.27"}

[[package]]
name = "urllib3"
version = "1.26.13"
optional = false

[metadata]
lock-version = "2.0"
python-versions = "^3.10"
EOF

# 5) Pipfile.lock — `==1.2.3` 에서 `==` 를 떼고, develop 은 담지 않는다.
cat > "$FIX/pipenv/Pipfile.lock" <<'EOF'
{
  "_meta": {"hash": {"sha256": "abc"}},
  "default": {
    "flask": {"version": "==2.2.2", "index": "pypi"},
    "jinja2": {"version": "==3.1.2"}
  },
  "develop": {
    "pytest": {"version": "==7.2.0"}
  }
}
EOF

# 6) 구식 setuptools 메타 — dist-info/METADATA 와 필드 구조가 같다(라이선스 fd 3 포함).
cat > "$FIX/py/lib/python3.11/site-packages/oldpkg-1.4.2.egg-info/PKG-INFO" <<'EOF'
Metadata-Version: 1.1
Name: oldpkg
Version: 1.4.2
Summary: legacy package
License: BSD-3-Clause
EOF

# 7) PEP 639 — `License-Expression:` 만 있는 패키지(요즘 배포판 다수). 복합 SPDX 표현식이 온다.
cat > "$FIX/py/lib/python3.11/site-packages/exprpkg-2.0.0.dist-info/METADATA" <<'EOF'
Metadata-Version: 2.4
Name: exprpkg
Version: 2.0.0
License-Expression: Apache-2.0 OR BSD-2-Clause
Summary: PEP 639 only
EOF

# 8) 둘 다 있는 패키지 — PEP 639 의 정식 필드인 License-Expression 이 이겨야 한다.
cat > "$FIX/py/lib/python3.11/site-packages/bothpkg-3.1.0.dist-info/METADATA" <<'EOF'
Metadata-Version: 2.4
Name: bothpkg
Version: 3.1.0
License: MIT License
License-Expression: MIT
Classifier: License :: OSI Approved :: MIT License
EOF

# 9) Classifier 만 있는 패키지 — `OSI Approved :: ` 를 뗀 값을 낸다. 중앙(VG_LICENSE_ALIASES)이
#    "BSD License" 를 BSD-3-Clause 로 정규화하므로 에이전트엔 매핑표를 두지 않는다.
#    `License: UNKNOWN` 은 setuptools 자리표시자라 라이선스로 세면 안 된다 — 여기서 같이 검사한다.
cat > "$FIX/py/lib/python3.11/site-packages/clspkg-0.9.0.dist-info/METADATA" <<'EOF'
Metadata-Version: 2.1
Name: clspkg
Version: 0.9.0
License: UNKNOWN
Classifier: License :: OSI Approved
Classifier: License :: OSI Approved :: BSD License
EOF

# 10) 배포판이 깐 파이썬 패키지 — `/usr/lib/python3/dist-packages` 처럼 루트 **바로 아래**에
#     `*.dist-info`/`*.egg-info` 가 놓인 형태. PROJECT_SCAN_ROOTS 밖이라 예전엔 통째로 안 잡혔다.
cat > "$FIX/sysdist/distpkg-4.5.6.dist-info/METADATA" <<'EOF'
Metadata-Version: 2.4
Name: distpkg
Version: 4.5.6
License-Expression: MIT
EOF
cat > "$FIX/sysdist/legacysys-1.0.egg-info/PKG-INFO" <<'EOF'
Metadata-Version: 1.1
Name: legacysys
Version: 1.0
License: BSD
EOF
# 11) 한 칸 더 들어간 메타는 **잡히면 안 된다** — 이 패스는 `-maxdepth 1` 로 루트 목록만 읽어
#     패키지 안까지 들어가지 않는다(ubuntu:24.04 실측 3,487개 파일 → 20개 항목). 여기가 뚫리면
#     비용 근거가 무너진다.
cat > "$FIX/sysdist/nested/deep-9.9.9.dist-info/METADATA" <<'EOF'
Metadata-Version: 2.4
Name: deep
Version: 9.9.9
License-Expression: MIT
EOF

PROJECT_SCAN_ROOTS="$FIX"
PY_SYS_META_ROOTS="$FIX/sysdist"
GOT=$(collect_project_deps_installed 3>>"$LIC")
# Pipfile.lock 분기는 기존 package-lock.json 과 같이 `have jq` 가드가 걸려 있다 — jq 가 없는 환경에선
#   그 두 줄만 빠지고 나머지는 그대로 검사한다(통째로 SKIP 하면 나머지 회귀를 놓친다).
WANT='npm|@babel/core|7.20.5
npm|@types/babel__core|7.1.20
npm|@types/node|18.11.9
npm|chalk|5.1.2
npm|lodash|4.17.21
npm|react-dom|18.2.0
npm|styled-components|5.3.6
pip|bothpkg|3.1.0
pip|clspkg|0.9.0
pip|distpkg|4.5.6
pip|exprpkg|2.0.0
pip|flask|2.2.2
pip|jinja2|3.1.2
pip|legacysys|1.0
pip|oldpkg|1.4.2
pip|requests|2.28.1
pip|urllib3|1.26.13'

rc=0
n_want=17
if ! have jq; then
  WANT=$(printf '%s\n' "$WANT" | grep -vE '^pip\|(flask|jinja2)\|')
  n_want=15
  echo "note node_python_locks: jq 없음 → Pipfile.lock 2건 제외하고 검사"
fi

if [ "$GOT" != "$WANT" ]; then
  echo "FAIL node_python_locks: 기대와 다름"
  diff <(printf '%s\n' "$WANT") <(printf '%s\n' "$GOT")
  rc=1
fi

# 오탐 확인 ① 스코프 이름이 `babel/core`·`core` 로 깨지지 않아야 한다.
if printf '%s\n' "$GOT" | grep -qE '^npm\|(babel/core|core|types/node)\|'; then
  echo "FAIL node_python_locks: 스코프 패키지 이름이 깨짐"
  rc=1
fi
# 오탐 확인 ② 범위·프로토콜·제약 표현이 이름/버전으로 새면 안 된다.
if printf '%s\n' "$GOT" | grep -qE '\^|~|>|<|npm:|workspace|file:|==|_react|\(' ; then
  echo "FAIL node_python_locks: 범위/프로토콜 표현이 유출됨"
  printf '%s\n' "$GOT" | grep -E '\^|~|>|<|npm:|workspace|file:|==|_react|\('
  rc=1
fi
# 오탐 확인 ③ 담지 않기로 한 항목이 들어오면 안 된다.
if printf '%s\n' "$GOT" | grep -qE 'pytest|should-not-appear|my-local|myapp|mylib|^pip\|deep\|'; then
  echo "FAIL node_python_locks: 제외 대상이 수집됨"
  rc=1
fi

# 라이선스 fd 3 — egg-info 의 `License:`(기존 동작)와 PEP 639 우선순위를 함께 검사한다.
#   exprpkg: License-Expression 만 → 복합 SPDX 표현식이 그대로 나가야 한다.
#   bothpkg: 둘 다 있음 → License(자유서술)가 아니라 License-Expression(MIT)이 이겨야 한다.
#   clspkg : Classifier 만(License 는 UNKNOWN 자리표시자) → `OSI Approved :: ` 를 뗀 값.
for want in 'pip|oldpkg|1.4.2|BSD-3-Clause' \
            'pip|exprpkg|2.0.0|Apache-2.0 OR BSD-2-Clause' \
            'pip|bothpkg|3.1.0|MIT' \
            'pip|clspkg|0.9.0|BSD License'             'pip|distpkg|4.5.6|MIT'             'pip|legacysys|1.0|BSD'; do
  if ! grep -qxF "$want" "$LIC"; then
    echo "FAIL node_python_locks: 라이선스 fd 3 에 '$want' 없음"
    cat "$LIC"
    rc=1
  fi
done
# UNKNOWN 자리표시자·`OSI Approved` 만 있는 불완전 Classifier 가 라이선스로 새면 안 된다.
if grep -qE '\|(UNKNOWN|OSI Approved)$' "$LIC"; then
  echo "FAIL node_python_locks: UNKNOWN/불완전 Classifier 가 라이선스로 유출됨"
  grep -E '\|(UNKNOWN|OSI Approved)$' "$LIC"
  rc=1
fi

# 배포판 파이썬 패스가 프로젝트 패스의 예산(SCAN_MAX_FILES)을 나눠 쓰지 않는다는 확인.
#   프로젝트 패스는 상한에 닿으면 `break 2` 로 통째로 끊기는데, 그때도 이 패스는 그대로 돌아야 한다.
#   반대로 두 패스를 한 스캔에 합쳐 두면 여기서 dist-packages 쪽이 함께 사라진다.
LIC2=$(mktemp "tests/.lic2-nplocks.XXXXXX") || exit 1
trap 'rm -rf "$FIX" "$LIC" "$LIC2"' EXIT
STARVED=$(SCAN_MAX_FILES=1 collect_project_deps_installed 3>>"$LIC2")
for want in 'pip|distpkg|4.5.6' 'pip|legacysys|1.0'; do
  if ! printf '%s
' "$STARVED" | grep -qxF "$want"; then
    echo "FAIL node_python_locks: 프로젝트 패스가 상한에 걸리자 배포판 파이썬 패스까지 끊겼다 ('$want' 없음)"
    rc=1
  fi
done

[ "$rc" -eq 0 ] && echo "OK  node_python_locks: ${n_want}건 일치 + 스코프/범위 유출 없음 + 라이선스 fd3(PEP 639 우선순위) + 배포판 파이썬 패스 예산 독립"
exit "$rc"
