#!/usr/bin/env bash
# collect_project_deps_installed() 의 Node/Python 보조 lock 소스 5종 검증.
#   yarn.lock(v1/v2+) · pnpm-lock.yaml · poetry.lock · Pipfile.lock · *.egg-info/PKG-INFO
# 에이전트 스크립트에서 함수 정의만 뽑아 eval 하므로 실제 배포되는 코드를 그대로 검사한다.
set -uo pipefail
cd "$(dirname "$0")/.."
AGENT=agent/vuln-inventory-agent.sh
export LC_ALL=C          # sort -u 결과 순서를 로케일과 무관하게 고정

have() { command -v "$1" >/dev/null 2>&1; }
eval "$(sed -n '/^emit_yarn_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_pnpm_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_poetry_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_gemfile_lock() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_gemspec_name() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_jar_meta() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^emit_nested_jars() {$/,/^}$/p' "$AGENT")"
eval "$(sed -n '/^collect_project_deps_installed() {$/,/^}$/p' "$AGENT")"
SCAN_MAX_FILES=3000; SCAN_MAX_DEPTH=12

FIX=$(mktemp -d "tests/.fixtures-nplocks.XXXXXX") || exit 1
LIC=$(mktemp "tests/.lic-nplocks.XXXXXX") || exit 1
trap 'rm -rf "$FIX" "$LIC"' EXIT
mkdir -p "$FIX/yarn1" "$FIX/yarn2" "$FIX/pnpm" "$FIX/poetry" "$FIX/pipenv" \
         "$FIX/py/lib/python3.11/site-packages/oldpkg-1.4.2.egg-info"

# 1) yarn v1(Classic) — 스코프 패키지의 다중 범위 헤더, 로컬(file:) 항목은 버려야 한다.
cat > "$FIX/yarn1/yarn.lock" <<'EOF'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.0.0, @babel/core@^7.1.0":
  version "7.20.5"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.20.5.tgz#abcdef"
  integrity sha512-deadbeef
  dependencies:
    "@babel/code-frame" "^7.18.6"
    lodash "^4.17.20"

lodash@^4.17.20:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591"

"my-local@file:../local-pkg":
  version "9.9.9"
EOF

# 2) yarn v2+(Berry) — 값에 따옴표가 없고 npm: 프로토콜이 붙는다. __metadata·workspace 는 버린다.
cat > "$FIX/yarn2/yarn.lock" <<'EOF'
__metadata:
  version: 6
  cacheKey: 8

"@types/node@npm:^18.0.0":
  version: 18.11.9
  resolution: "@types/node@npm:18.11.9"
  languageName: node

"chalk@npm:^5.0.0":
  version: 5.1.2
  resolution: "chalk@npm:5.1.2"

"myapp@workspace:.":
  version: 0.0.0-use.local
  resolution: "myapp@workspace:."
EOF

# 3) pnpm — v6 `@` 표기와 v5 슬래시+피어 표기가 섞여도 이름이 안 깨져야 한다.
#    snapshots:(v9) 는 packages 와 같은 키를 중복하므로 읽지 않는다.
cat > "$FIX/pnpm/pnpm-lock.yaml" <<'EOF'
lockfileVersion: '6.0'

dependencies:
  lodash:
    specifier: ^4.17.20
    version: 4.17.21

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}
    dev: false

  /@babel/core@7.20.5:
    resolution: {integrity: sha512-def}

  /@types/babel__core@7.1.20:
    resolution: {integrity: sha512-ghi}

  /react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-jkl}

  /styled-components/5.3.6_react@17.0.2:
    resolution: {integrity: sha512-mno}

  /mylib@file:../mylib:
    resolution: {directory: ../mylib}

snapshots:

  /should-not-appear@9.9.9:
    resolution: {integrity: sha512-zzz}
EOF

# 4) poetry — [[package]] 다중 블록. 하위 테이블([package.dependencies]) 값이 새면 안 된다.
cat > "$FIX/poetry/poetry.lock" <<'EOF'
[[package]]
name = "requests"
version = "2.28.1"
description = "Python HTTP for Humans."
optional = false

[package.dependencies]
certifi = ">=2017.4.17"
urllib3 = {version = ">=1.21.1,<1.27"}

[[package]]
name = "urllib3"
version = "1.26.13"
optional = false

[metadata]
lock-version = "2.0"
python-versions = "^3.10"
EOF

# 5) Pipfile.lock — `==1.2.3` 에서 `==` 를 떼고, develop 은 담지 않는다.
cat > "$FIX/pipenv/Pipfile.lock" <<'EOF'
{
  "_meta": {"hash": {"sha256": "abc"}},
  "default": {
    "flask": {"version": "==2.2.2", "index": "pypi"},
    "jinja2": {"version": "==3.1.2"}
  },
  "develop": {
    "pytest": {"version": "==7.2.0"}
  }
}
EOF

# 6) 구식 setuptools 메타 — dist-info/METADATA 와 필드 구조가 같다(라이선스 fd 3 포함).
cat > "$FIX/py/lib/python3.11/site-packages/oldpkg-1.4.2.egg-info/PKG-INFO" <<'EOF'
Metadata-Version: 1.1
Name: oldpkg
Version: 1.4.2
Summary: legacy package
License: BSD-3-Clause
EOF

PROJECT_SCAN_ROOTS="$FIX"
GOT=$(collect_project_deps_installed 3>>"$LIC")
# Pipfile.lock 분기는 기존 package-lock.json 과 같이 `have jq` 가드가 걸려 있다 — jq 가 없는 환경에선
#   그 두 줄만 빠지고 나머지는 그대로 검사한다(통째로 SKIP 하면 나머지 회귀를 놓친다).
WANT='npm|@babel/core|7.20.5
npm|@types/babel__core|7.1.20
npm|@types/node|18.11.9
npm|chalk|5.1.2
npm|lodash|4.17.21
npm|react-dom|18.2.0
npm|styled-components|5.3.6
pip|flask|2.2.2
pip|jinja2|3.1.2
pip|oldpkg|1.4.2
pip|requests|2.28.1
pip|urllib3|1.26.13'

rc=0
n_want=12
if ! have jq; then
  WANT=$(printf '%s\n' "$WANT" | grep -vE '^pip\|(flask|jinja2)\|')
  n_want=10
  echo "note node_python_locks: jq 없음 → Pipfile.lock 2건 제외하고 검사"
fi

if [ "$GOT" != "$WANT" ]; then
  echo "FAIL node_python_locks: 기대와 다름"
  diff <(printf '%s\n' "$WANT") <(printf '%s\n' "$GOT")
  rc=1
fi

# 오탐 확인 ① 스코프 이름이 `babel/core`·`core` 로 깨지지 않아야 한다.
if printf '%s\n' "$GOT" | grep -qE '^npm\|(babel/core|core|types/node)\|'; then
  echo "FAIL node_python_locks: 스코프 패키지 이름이 깨짐"
  rc=1
fi
# 오탐 확인 ② 범위·프로토콜·제약 표현이 이름/버전으로 새면 안 된다.
if printf '%s\n' "$GOT" | grep -qE '\^|~|>|<|npm:|workspace|file:|==|_react|\(' ; then
  echo "FAIL node_python_locks: 범위/프로토콜 표현이 유출됨"
  printf '%s\n' "$GOT" | grep -E '\^|~|>|<|npm:|workspace|file:|==|_react|\('
  rc=1
fi
# 오탐 확인 ③ 담지 않기로 한 항목이 들어오면 안 된다.
if printf '%s\n' "$GOT" | grep -qE 'pytest|should-not-appear|my-local|myapp|mylib'; then
  echo "FAIL node_python_locks: 제외 대상이 수집됨"
  rc=1
fi

# egg-info 도 METADATA 와 동일하게 라이선스를 fd 3 으로 내보내야 한다.
if ! grep -qx 'pip|oldpkg|1.4.2|BSD-3-Clause' "$LIC"; then
  echo "FAIL node_python_locks: egg-info 라이선스가 fd 3 으로 안 나감"
  cat "$LIC"
  rc=1
fi

[ "$rc" -eq 0 ] && echo "OK  node_python_locks: ${n_want}건 일치 + 스코프/범위 유출 없음 + egg-info 라이선스 fd3"
exit "$rc"
